version: '2'
services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/go/src/goraphql
    ports:
      - 8080:8080
    command: go run app/main.go
  mysql:
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file: .env
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql